// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: order_fab.create.sql

package sqlc

import (
	"context"
)

const createOrderFAB = `-- name: CreateOrderFAB :exec
INSERT INTO order_fabs (
    order_id,
    fab_id,
    quantity
) VALUES (
    $1, $2, $3
)
`

type CreateOrderFABParams struct {
	OrderID  int32 `json:"order_id"`
	FabID    int32 `json:"fab_id"`
	Quantity int32 `json:"quantity"`
}

func (q *Queries) CreateOrderFAB(ctx context.Context, arg CreateOrderFABParams) error {
	_, err := q.db.Exec(ctx, createOrderFAB, arg.OrderID, arg.FabID, arg.Quantity)
	return err
}
