// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: order.update.sql

package sqlc

import (
	"context"
)

const updateOrderStatusByOrderId = `-- name: UpdateOrderStatusByOrderId :exec
UPDATE orders
SET 
    status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateOrderStatusByOrderIdParams struct {
	ID     int32         `json:"id"`
	Status OrderStatuses `json:"status"`
}

func (q *Queries) UpdateOrderStatusByOrderId(ctx context.Context, arg UpdateOrderStatusByOrderIdParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatusByOrderId, arg.ID, arg.Status)
	return err
}
