// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: order_seat.create.sql

package sqlc

import (
	"context"
)

const createOrderSeat = `-- name: CreateOrderSeat :exec
INSERT INTO order_seats (
    order_id,
    seat_id,
    price
) VALUES (
    $1, $2, $3
)
`

type CreateOrderSeatParams struct {
	OrderID int32 `json:"order_id"`
	SeatID  int32 `json:"seat_id"`
	Price   int32 `json:"price"`
}

func (q *Queries) CreateOrderSeat(ctx context.Context, arg CreateOrderSeatParams) error {
	_, err := q.db.Exec(ctx, createOrderSeat, arg.OrderID, arg.SeatID, arg.Price)
	return err
}
