// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: order.create.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    ordered_by,
    showtime_id,
    show_date,
    status,
    note
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id
`

type CreateOrderParams struct {
	OrderedBy  string        `json:"ordered_by"`
	ShowtimeID int32         `json:"showtime_id"`
	ShowDate   pgtype.Date   `json:"show_date"`
	Status     OrderStatuses `json:"status"`
	Note       string        `json:"note"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int32, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderedBy,
		arg.ShowtimeID,
		arg.ShowDate,
		arg.Status,
		arg.Note,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
