// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injectors

import (
	"bmt_order_service/db/sqlc"
	"bmt_order_service/internal/controllers"
	"bmt_order_service/internal/implementations/message_broker/readers"
	"bmt_order_service/internal/implementations/order"
	"bmt_order_service/internal/implementations/redis"
	"bmt_order_service/internal/injectors/provider"
)

// Injectors from message_broker.wire.go:

func InitMessageBroker() (*readers.MessageBrokerReader, error) {
	pool := provider.ProvidePgxPool()
	iStore := sqlc.NewStore(pool)
	iRedis := redis.NewRedisClient()
	messageBrokerReader := readers.NewMessageBrokerReader(iStore, iRedis)
	return messageBrokerReader, nil
}

// Injectors from order_controller.wire.go:

func InitOrderController() (*controllers.OrderController, error) {
	pool := provider.ProvidePgxPool()
	iStore := sqlc.NewStore(pool)
	iRedis := redis.NewRedisClient()
	iOrder := order.NewOrderService(iStore, iRedis)
	orderController := controllers.NewOrderController(iOrder)
	return orderController, nil
}
